### ISSUE TITLE
Creating Async calls from main thread gives an error

### ISSUE THREAD

**Issue by EdwardSeley** [tompmstephenson/LazyChef#1]
```
2019-04-11 23:07:24.473 32158-32158/com.example.thomasstephenson.lazychef E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.thomasstephenson.lazychef, PID: 32158
    java.lang.IllegalStateException: Cannot access database on the main thread since it may potentially lock the UI for a long period of time.
        at android.arch.persistence.room.RoomDatabase.assertNotMainThread(RoomDatabase.java:204)
        at android.arch.persistence.room.RoomDatabase.beginTransaction(RoomDatabase.java:251)
        at com.example.thomasstephenson.lazychef.RecipeDao_RecipeDatabase_Impl.insert(RecipeDao_RecipeDatabase_Impl.java:111)
        at com.example.thomasstephenson.lazychef.Recipe.saveRecipe(Recipe.java:99)
        at com.example.thomasstephenson.lazychef.RecipeDetailsActivity$1.onClick(RecipeDetailsActivity.java:28)
        at android.view.View.performClick(View.java:6886)
        at android.widget.TextView.performClick(TextView.java:12651)
        at android.view.View$PerformClick.run(View.java:26083)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6938)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

**Comment by tps48** [comment]
Solution: make all database calls from an async subclass.
